api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "cart-trancform"
type = "function"
uid = "7f0b8fdc-063e-ddb2-f22e-7970ba758f76ca16e682"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
