api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "payment-custom"
type = "function"
uid = "a9f49ca3-7b69-14d2-3168-7971066f17ae6f97e725"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.payment-methods.transform.run"
  input_query = "src/cart_payment_methods_transform_run.graphql"
  export = "cart-payment-methods-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
